### ISSUE TITLE
User Auth Completion

### ISSUE THREAD

**Issue by kennyxli** [kennyxli/Amazone#6]

**Comment by danemauland** [comment]
Hey Kenny, good first pass at the user auth styling. Below are the discrepancies I noticed:

# Splash
## Upper Navbar
Navbar height is off
Most things in your navbar are bigger than on Amazon, especially font sizes
Hardcode in a placeholder for the 0 for the cart for now, add in functionality for that later
Cursor doesn't change when mousing over buttons
Search bar border should extend around the search icon when the search input is focused
When clicking into the search bar, the text cursor is all the way to the left. Amazon has it placed indented in a little.

## Lower Navbar
Font weight looks off
If these are all going to be functional, spread them out so they take up the whole navbar. If they're not going to be functional, add in other non-functional links to take up the whole nav bar
Mousing over the links pushes the other links to the right
Change color of your GitHub and LinkedIn links so they stand out more

## Body
Amazon's version of this is tighter towards the center
Font size and/or weight looks off
Links are missing padding between themselves and the image
Link color is off
Links are missing color change on hover

# Sign in
Your logo looks too big
padding between the border of the form and the form itself is off
Font sizes look off
text input focus effect is missing
Hover effects on buttons missing
Their buttons appear to have a gradient
Formatting for your links is off (color, underline, hover effects)
Using dashes to create a straight line is gross and you can do much better

# Sign up
Review sign in notes for this
Missing right pointing arrow on sign-in link
Text at the bottom should be horizontally aligned with your inputs/rest of the form
Your gradient is really good--I'm not going to be too picky on this, but see if you can get it a little bit lighter and have the effect spread out further.
## Errors
Format this to handle multiple errors better. The errors are also off-center

# Post log-in
Very nice touch grabbing the location. Keep in mind that some users have different policy settings that won't allow you to grab their location--if you don't already, check to make sure you're able to get the user's location from browser, and if you can't, then just have the default "select your address text".

**Comment by danemauland** [comment]
Great progress! A few more comments:

# Splash
## Upper Navbar
The search bar appears to have a border or something right below it
When mousing over elements to the right of the nav bar, the bottom border is too far down (most evident when mousing over "Returns & orders")

## Lower Navbar
Font weight still looks too heavy

## Body

Compare your positioning of the squares here to Amazon. Yours are spread out horizontally across the whole page. Amazon has them grouped more towards the center.

# Sign in
Hover and click effect on "Create your Amazone account" button is missing

## Errors
This still doesn't display multiple errors well. Have all errors inside the same "There was a problem" box if there are multiple errors.
