### ISSUE TITLE
Searchbar, product search page, product page review

### ISSUE THREAD

**Issue by kennyxli** [kennyxli/Amazone#8]
Searchbar, product search page and product page are not pixel perfect. Definitely cut some corners but presentable. Going to move onto my next 2 MVP's so i can get them done by Friday.

Fixed up the issues for auth and homepage

**Comment by danemauland** [comment]
# Search
## Search dropdown
I wouldn't want to present this as-is. This is something you can/should make pixel perfect, please take a break from the remaining MVPs and revisit this. I get that you want to get the remaining MVPs done by Friday, but it's better to have a non-existant feature than one that looks rushed/not fully professional. Also make sure that the dropdown disappears when the search box is no longer focused
## Search page
The h1 containing the # of results for the search term should be farther to the right, the rest of this is great

# Product Page
Content-wise this page is fine. You just need to polish up the styling.
Set a max-width of ~1500 for the content (including the sidebar) on this page. Whatever div has this constraint should be centered. This will help to fill the page vertically and make it look like there's more here.
You're already showing the star rating on the search page. I'd imagine it should be pretty easy to re-use that code here and it gives a little more content. 
Location of the prime logo in the main content area looks a little clunky here. Consider adding a little more spacing between it and the price.

## Sidebar
Fix size of the quantity dropdown, it currently cuts off the number
You can't have the other buttons looking as good as they do while having these buttons look like this. Make these buttons pixel perfect (with similar icons). This should be low-hanging fruit considering the styling you've already done for auth buttons.

**Comment by danemauland** [comment]
## Search dropdown
Missing border on top of search dropdown
Text that matches the input should be normal font-weight. Text that doesn't match should be bolded
Clicking a result in the search dropdown should fill the search box with that text

## Search page
The top shouldn't have a border
The left border looks too thin

### Side bar
Make these buttons better, you already have most of the CSS written for the styling for the auth pages
